### ISSUE TITLE
No se actualiza para confirmar los envios a ERC20

### ISSUE THREAD

**Issue by anibalbado2015** [ccndevelopers/tokenconnect#2]
buenas noches...
me da error al querer mandar las fichas a las cuenta ERC-20
me produce una falla al enviar
https://ropsten.etherscan.io/tx/0x5a0036ebc8b28a04fb62bd7eb04c00ee60661a67ced6140b7e5a7fc7ced45a7c

"Las transacciones fueron enviadas. Ahora espere hasta que todas las transacciones sean minadas".

TxHash: 0xa016760b30c2408f63d3e476548e9b3c80547454cc9b005f6d5fefbf931fab14 
Aprobar TokenConnect para gastar 200000. CCN Estado de los tokens : 

TxHash: 0x5a0036ebc8b28a04fb62bd7eb04c00ee60661a67ced6140b7e5a7fc7ced45a7c 
TokenConnect Distributing 200000. CCN Estado de los tokens :

**Comment by ccndevelopers** [comment]
Please post in English

**Comment by anibalbado2015** [comment]
Goodnight ...
I get an error when I want to send the chips to the ERC-20 account
I get a failure to send
https://ropsten.etherscan.io/tx/0x5a0036ebc8b28a04fb62bd7eb04c00ee60661a67ced6140b7e5a7a7a7a7a45a7c

"The transactions were sent, now wait until all the transactions are mined."

TxHash: 0xa016760b30c2408f63d3e476548e9b3c80547454cc9b005f6d5fefbf931fab14
Approve TokenConnect to spend 200000. CCN Status of the tokens:

TxHash: 0x5a0036ebc8b28a04fb62bd7eb04c00ee60661a67ced6140b7e5a7fc7ced45a7c
TokenConnect Distributing 200000. CCN Status of the tokens:
![1](https://user-images.githubusercontent.com/39341370/55288733-10945d00-5392-11e9-93a4-de1218f36fbf.JPG)

**Comment by ccndevelopers** [comment]
We have evaluated you were including the sender address in CSV file "0x0b23d20131e64f84b78eff409ef0aa8912ee30b9" that cause the transaction failure. As in practical scenario, the sender does not send the tokens to themselves. We will add a filter to remove own address automatically if found in CSV. 
Moreover, the issue is not related to the tokenconnect app it is related to CCN tokens that are hardcoded to not allow a transaction where sender and receiver are the same because that is just waste of time.

**Comment by anibalbado2015** [comment]
y mi bono por encontrar la falla?

**Comment by ccndevelopers** [comment]
prize distribution after 2 weeks

**Comment by ccndevelopers** [comment]
please leave your ERC-20 address over 
info@customcontract.network

**Comment by anibalbado2015** [comment]
0xc76366B9706e2dfdB14d09562E7C386e8Ed279aF

Isidro Anibal Bado
Soporte Remoto 24hs
Cel: 2234381524
Mar del plata - Buenos Aires


________________________________
De: ccndevelopers <notifications@github.com>
Enviado: domingo, 12 de mayo de 2019 03:06
Para: ccndevelopers/tokenconnect
Cc: anibalbado2015; Comment
Asunto: Re: [ccndevelopers/tokenconnect] No se actualiza para confirmar los envios a ERC20 (#2)


please leave your ERC-20 address over
info@customcontract.network<mailto:info@customcontract.network>
